spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loandb
    username: kasutaja
    password: parool
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  loan:
    max-customer-age: 70
    min-amount: 5000
    min-term-months: 6
    max-term-months: 360

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
